#!/bin/bash
# Note: Late:  this file is placed in this directory as an example of 
# how some stuff is done.  
# IN this file I need to set a list of variables
# that contain the chars in file names that I don't want
# eg: swp for vi swap files, 
# eg v8Flags ???? why ???
# others ???
#
# ====================================
#
cd /Users/maatkins/
dirList=`ls -ad .*`
swpFile=".swp"

# echo $dirList

for f in $dirList

do
 if [ -f $f ]
   then
 
     if echo $f | grep -q $swpFile
       then
         echo "Do nothing to the swp file  " $f
       else
        cp $f /Users/maatkins/tmp/null
     fi
 fi
done
