update USER_ENTITLEMENT SET MAX_TRAN_AMT = 6500;

SELECT * FROM USER_ENTITLEMENT Order by MAX_DAILY_CUMULATIVE_LIMIT DESC ;

update USER_ENTITLEMENT SET MAX_TRAN_AMT = 6500
WHERE function_name like 'CREATE_%' and user_id in (select user_id from  USER_ENTITLEMENT where MAX_TRAN_AMT != 6500);

update USER_ENTITLEMENT SET MAX_DAILY_CUMULATIVE_LIMIT = 10000
WHERE function_name like 'CREATE_%' and user_id in (select user_id from  USER_ENTITLEMENT where MAX_DAILY_CUMULATIVE_LIMIT != 10000);