INSERT INTO "MURENTITLE"."USER_ACCOUNT_ENTITLEMENT" 
 (ACCOUNT_IDENTIFIER, USER_ID, ENTITLEMENT_NAME) 
  VALUES ('20130880', '1352546', 'VIEW_PAYMENT_FPS');


INSERT INTO "MURENTITLE"."USER_ACCOUNT_ENTITLEMENT" 
 (ACCOUNT_IDENTIFIER, USER_ID, ENTITLEMENT_NAME) 
  VALUES ('20130880', '1352546', 'CREATE_PAYMENT_FPS');
  
  commit ;
  
  
  Select * from  "MURENTITLE"."USER_ACCOUNT_ENTITLEMENT" 
   where USER_ID = '1352546' order by ENTITLEMENT_NAME ;
   
   
   Select * from  "MURENTITLE"."USER_ENTITLEMENT" 
   where USER_ID = '1352546' ;