#!/bin/bash
# Deprecated in favor of a function in ~/.bashrc with same name as this file

REPO_DIRECTORIES="svb-*"

# echo $REPO_DIRECTORIES

for f in $REPO_DIRECTORIES
	do
		if [ -d "$f" ]
		then
		#	echo echoing whats in DollarF ; echo $f
			echo "************************************************"
			echo "************************************************"
			cd $f
			pwd
			git pull
			cd ~/
			echo
			echo

		else 
			echo NotWorking
		fi
	done

echo done!
