#! /bin/bash # # So the idea here is to updae the Notes directory wrt git # will do git add, git commit, git push   acp # commit will use a date string
#
 varDateNow=$(date +%m-%d-%Y_%H:%M:%S)
# commit -m nowVar *.txt *.pdf
#
#git status
echo echoing git status
echo Sleeping 5 sec
sleep 5

#git add *
echo echoing "add *  -all"
echo Sleeping 5 sec
sleep 5


#git commit -m $varDateNow 
echo echoing commit -m $varDateNow
echo Sleeping 5 sec
sleep 5

echo $varDateNow
