@echo off

call "PsKill ALL Eclipse.bat"
call "PsKill ALL IE.bat"
call "PsKill ALL OF Chrome .bat"
call "PsKill ALL OF FireFox.bat"
call "PsKill ALL OF GitKraken .bat"
call "PsKill ALL Task Mgrs.bat "
call "PsKill CitrixDevConnect.bat"
call "PsKill GitBash.bat "
call "PsKill MightyTextApp.bat "
call "PsKill MsOutlook.bat "
call "PsKill only Test Drivers Chrome.bat"
call "PsKill SkypeLync.bat "
call "PsKill TeamsApp.bat"
call "PsKill VIPApp.bat "
call "PsKill VLC.bat"
call "PsKill TeamsApp.bat"
call "PsKill chromeDrivers.bat"

